### ISSUE TITLE
Submitting a hierarchy for gd T cell subsets

### ISSUE THREAD

**Issue by jig2125** [donnafarberlab/MMoCHi#2]
**Name**
Human gd T cell Vd subset classification v1

**Short description**
Classifer for the subsetting gd T cells into Vd1,  Vd2 or 'other'

**Paired modalities**
scRNA-seq - Gene expression (no modifier) 

**Feature set details**
Aligned to GRCh38 with Gencode v24 annotation

**Species**
_Homo sapiens_

**Sample or dataset details**
Pediatric gd T cells sorted from spleen, lung, lung-associated lymph node, jejunum lamina propria and mesenteric lymph nodes. Additional adult samples from equivalent tissues extracted from (doi: https://doi.org/10.1101/2023.07.06.547944)

**Author(s)**
Joshua I. Gray

**Publication**
N/A

**Additional details**
With additional cells this could be fine tuned to include less common Vd subsets (e.g.) Vd3, as well as adding Vg chain classification to fully elucidate the TCR pairings of gd T cell subsets. Addition of scTCRseq data would further improve this resolution.

**Example code to build the hierarchy**

```
h= mmc.Hierarchy()

h.add_classification('tcr','All',['TRDV1','TRDV2','TRDV3','TRAV38-2DV8','TRAV23DV6','TRAV29DV5','TRAV36DV7','TRAV14DV4'],)
h.add_subset('vd1','tcr',dict(pos=['TRDV1'],neg=['TRDV2','TRDV3', 'TRAV38-2DV8','TRAV23DV6','TRAV29DV5','TRAV36DV7','TRAV14DV4']))
h.add_subset('vd2','tcr',dict(pos=['TRDV2'],neg=['TRDV1','TRDV3','TRAV38-2DV8','TRAV23DV6','TRAV29DV5','TRAV36DV7','TRAV14DV4']))
h.add_subset('other','tcr',dict(any_of=['TRDV3','TRAV38-2DV8','TRAV23DV6','TRAV29DV5','TRAV36DV7','TRAV14DV4'],neg=['TRDV1','TRDV2']))
```

**Comment by Daniel-Caron** [comment]
Added. Thank you!

**Comment by nroak** [comment]
This is a great tool! Thank you for development. Can you please generate/provide similar T subset resources for mouse datasets? It will be greatly useful as many labs including ours generate CITE-seq data from mouse models.

Also, has it been accepted in any journals yet? Looking forward to final publication.
